<template>
	<div>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
		<h2>Sports页面</h2>
	</div>
</template>

<script>
	export default{
		name:"Sports"
	}
</script>

<style>
</style>
